### ISSUE TITLE
installing from usb drive /dev/disk/by-label issues

### ISSUE THREAD

**Issue by plaguewolf** [CarlDuff/architect#3]
formatted and iso loaded to usb drive in windows, unable to set label to architect*

label auto sets to UUI for soem reason, and on boot in UEFI i get the unable to find disk by lable as expected.

what do? symlink? what to where?

**Comment by plaguewolf** [comment]
sigh.
twas the tool i used, though i have yet to confirm it by booting

using rufus, i didnt know one could Alt + F to allow usbHDD. hopefully rufus will make the proper label.

**Comment by CarlDuff** [comment]
This may help you: https://plus.google.com/111896149918903369238/posts/YJtsFActmYu

**Comment by plaguewolf** [comment]
thanks, i actually worked it out on my own

just;

cd /dev/disk/by-label
then sym link the UUI to the expected source, weird though, i guess MS doesnt allow long disk labels
