### ISSUE TITLE
missing wirless driver.

### ISSUE THREAD

**Issue by steverweber** [CarlDuff/architect#4]
```
02:00.0 Network controller: Broadcom Corporation BCM4360 802.11ac Wireless Network Adapter (rev 03)
driver: brcmfmac might do the trick. 
```
likely more drivers... 

These drivers are kinda necessary on laptops that dont have on board Ethernet.

**Comment by CarlDuff** [comment]
All available drivers for wifi devices are included in the ISO - unfortunately Arch does not have the same broad support as distros like Debian or Ubuntu...

**Comment by aldorgan** [comment]
my RTL8723BE PCIe Wireless Network Adapter or the rt2870 usb wifi adapter is detected by the installer. so i have no way to install Architect linux except using a ethernet cable but that is no option for me at the time being.

**Comment by steverweber** [comment]
@aldorgan 'is detected by installer?'

**Comment by steverweber** [comment]
@CarlDuff  i don't have problems getting my wireless to work in arch.  Just the installer did not pick it up.
I'll investigate more. perhaps issue: https://bugzilla.kernel.org/show_bug.cgi?id=100201
Thanks.

**Comment by CarlDuff** [comment]
Hmm. Please try this: try to connect to wifi again. If it fails, enter the
following command and post the output:
# ip link

**Comment by aldorgan** [comment]
Update: if use the ctrl -z or something like that so i can exit out to the terminal and run ifconfig -a i can see the interfaces for both of the cards, but the installer can not pick them up.

**Comment by CarlDuff** [comment]
So what is the output of
ip link

**Comment by aldorgan** [comment]
4: wlp0s20u3: <BROADCAST, MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000 link/ether 14:d6:4d:48:ac:7c brd ff:ff:ff:ff:ff:ff

**Comment by steverweber** [comment]
when i hot-plugged my eth adapter, i needed to exit the install wizard and run..
```
dhcpd
/initialise
```
but ya I could have just rebooted the computer and the network likely would have come up.
