### ISSUE TITLE
Where to download iso?

### ISSUE THREAD

**Issue by mabushey** [CarlDuff/architect#7]
Where do I get an iso to install?

**Comment by rjslinux** [comment]
From the home page - http://apricityos.com

There is a download link there for the ISO image or the torrent

**Comment by mabushey** [comment]
What the hell is apricityos??

**Comment by mabushey** [comment]
After lots of googling I finally found it. I figured out why it's hidden. This installer makes a manual Arch install look simple and efficient. Why would anyone waste their time to create a super complicated Arch installer? Does this have any advantages over the standard manual Arch install? Is Yougurt installed with this installer?

**Comment by CarlDuff** [comment]
Hello,

The ISOs and Torrents can be obtained here (and only here): http://sourceforge.net/projects/architect-linux/

I'm afraid the installer does not provide any yoghurt, or any other dairy products at all - lol
As for AUR helpers like yaourt, these are not provided as the installer is pure Arch only, and these sorts of packages are not provided by the official repository.

Whether or not the installer is advantageous to use will depend on the views and needs of the user, to be honest.
